name: city_guide_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  build_runner: ^2.1.11
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  firebase_auth: ^3.3.18
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^1.0.3
  geolocator: ^8.2.1
  google_maps_flutter: ^2.1.5
  json_annotation: ^4.5.0
  location: ^4.4.0
  shared_preferences: ^2.0.15
  uuid: ^3.0.6

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  json_serializable: ^6.2.0
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
